# -*- coding:utf-8 -*-

# _____________________________________________________________________________
#                                                                       Imports

from libc.stdint cimport uint8_t, uint32_t

# _____________________________________________________________________________
#                                                                  External API

cdef extern from "pcre2.h":

    # Option bits passed to pcre2_compile().
    cdef unsigned int ALLOW_EMPTY_CLASS "PCRE2_ALLOW_EMPTY_CLASS"
    cdef unsigned int ALT_BSUX "PCRE2_ALT_BSUX"
    cdef unsigned int AUTO_CALLOUT "PCRE2_AUTO_CALLOUT"
    cdef unsigned int CASELESS "PCRE2_CASELESS"
    cdef unsigned int DOLLAR_ENDONLY "PCRE2_DOLLAR_ENDONLY"
    cdef unsigned int DOTALL "PCRE2_DOTALL"
    cdef unsigned int DUPNAMES "PCRE2_DUPNAMES"
    cdef unsigned int EXTENDED "PCRE2_EXTENDED"
    cdef unsigned int FIRSTLINE "PCRE2_FIRSTLINE"
    cdef unsigned int MATCH_UNSET_BACKREF "PCRE2_MATCH_UNSET_BACKREF"
    cdef unsigned int MULTILINE "PCRE2_MULTILINE"
    cdef unsigned int NEVER_UCP "PCRE2_NEVER_UCP"
    cdef unsigned int NEVER_UTF "PCRE2_NEVER_UTF"
    cdef unsigned int NO_AUTO_CAPTURE "PCRE2_NO_AUTO_CAPTURE"
    cdef unsigned int NO_AUTO_POSSESS "PCRE2_NO_AUTO_POSSESS"
    cdef unsigned int NO_DOTSTAR_ANCHOR "PCRE2_NO_DOTSTAR_ANCHOR"
    cdef unsigned int NO_START_OPTIMIZE "PCRE2_NO_START_OPTIMIZE"
    cdef unsigned int UCP "PCRE2_UCP"
    cdef unsigned int UNGREEDY "PCRE2_UNGREEDY"
    cdef unsigned int UTF "PCRE2_UTF"
    cdef unsigned int NEVER_BACKSLASH_C "PCRE2_NEVER_BACKSLASH_C"
    cdef unsigned int ALT_CIRCUMFLEX "PCRE2_ALT_CIRCUMFLEX"
    cdef unsigned int ALT_VERBNAMES "PCRE2_ALT_VERBNAMES"
    cdef unsigned int USE_OFFSET_LIMIT "PCRE2_USE_OFFSET_LIMIT"
    cdef unsigned int EXTENDED_MORE "PCRE2_EXTENDED_MORE"
    cdef unsigned int LITERAL "PCRE2_LITERAL"
    cdef unsigned int MATCH_INVALID_UTF "PCRE2_MATCH_INVALID_UTF"

    # Request types for pcre2_pattern_info().
    cdef unsigned int INFO_ALLOPTIONS "PCRE2_INFO_ALLOPTIONS"
    cdef unsigned int INFO_ARGOPTIONS "PCRE2_INFO_ARGOPTIONS"
    cdef unsigned int INFO_BACKREFMAX "PCRE2_INFO_BACKREFMAX"
    cdef unsigned int INFO_BSR "PCRE2_INFO_BSR"
    cdef unsigned int INFO_CAPTURECOUNT "PCRE2_INFO_CAPTURECOUNT"
    cdef unsigned int INFO_FIRSTCODEUNIT "PCRE2_INFO_FIRSTCODEUNIT"
    cdef unsigned int INFO_FIRSTCODETYPE "PCRE2_INFO_FIRSTCODETYPE"
    cdef unsigned int INFO_FIRSTBITMAP "PCRE2_INFO_FIRSTBITMAP"
    cdef unsigned int INFO_HASCRORLF "PCRE2_INFO_HASCRORLF"
    cdef unsigned int INFO_JCHANGED "PCRE2_INFO_JCHANGED"
    cdef unsigned int INFO_JITSIZE "PCRE2_INFO_JITSIZE"
    cdef unsigned int INFO_LASTCODEUNIT "PCRE2_INFO_LASTCODEUNIT"
    cdef unsigned int INFO_LASTCODETYPE "PCRE2_INFO_LASTCODETYPE"
    cdef unsigned int INFO_MATCHEMPTY "PCRE2_INFO_MATCHEMPTY"
    cdef unsigned int INFO_MATCHLIMIT "PCRE2_INFO_MATCHLIMIT"
    cdef unsigned int INFO_MAXLOOKBEHIND "PCRE2_INFO_MAXLOOKBEHIND"
    cdef unsigned int INFO_MINLENGTH "PCRE2_INFO_MINLENGTH"
    cdef unsigned int INFO_NAMECOUNT "PCRE2_INFO_NAMECOUNT"
    cdef unsigned int INFO_NAMEENTRYSIZE "PCRE2_INFO_NAMEENTRYSIZE"
    cdef unsigned int INFO_NAMETABLE "PCRE2_INFO_NAMETABLE"
    cdef unsigned int INFO_NEWLINE "PCRE2_INFO_NEWLINE"
    cdef unsigned int INFO_DEPTHLIMIT "PCRE2_INFO_DEPTHLIMIT"
    cdef unsigned int INFO_RECURSIONLIMIT "PCRE2_INFO_RECURSIONLIMIT"
    cdef unsigned int INFO_SIZE "PCRE2_INFO_SIZE"
    cdef unsigned int INFO_HASBACKSLASHC "PCRE2_INFO_HASBACKSLASHC"
    cdef unsigned int INFO_FRAMESIZE "PCRE2_INFO_FRAMESIZE"
    cdef unsigned int INFO_HEAPLIMIT "PCRE2_INFO_HEAPLIMIT"
    cdef unsigned int INFO_EXTRAOPTIONS "PCRE2_INFO_EXTRAOPTIONS"

    # Option bits passed to pcre2_jit_compile().
    cdef unsigned int JIT_COMPLETE "PCRE2_JIT_COMPLETE"
    cdef unsigned int JIT_PARTIAL_SOFT "PCRE2_JIT_PARTIAL_SOFT"
    cdef unsigned int JIT_PARTIAL_HARD "PCRE2_JIT_PARTIAL_HARD"
    cdef unsigned int JIT_INVALID_UTF "PCRE2_JIT_INVALID_UTF"

    # Option bits passed to pcre2_match() and pcre2_substitute().
    cdef unsigned int NOTBOL "PCRE2_NOTBOL"
    cdef unsigned int NOTEOL "PCRE2_NOTEOL"
    cdef unsigned int NOTEMPTY "PCRE2_NOTEMPTY"
    cdef unsigned int NOTEMPTY_ATSTART "PCRE2_NOTEMPTY_ATSTART"
    cdef unsigned int PARTIAL_SOFT "PCRE2_PARTIAL_SOFT"
    cdef unsigned int PARTIAL_HARD "PCRE2_PARTIAL_HARD"
    cdef unsigned int DFA_RESTART "PCRE2_DFA_RESTART"
    cdef unsigned int DFA_SHORTEST "PCRE2_DFA_SHORTEST"
    cdef unsigned int SUBSTITUTE_GLOBAL "PCRE2_SUBSTITUTE_GLOBAL"
    cdef unsigned int SUBSTITUTE_EXTENDED "PCRE2_SUBSTITUTE_EXTENDED"
    cdef unsigned int SUBSTITUTE_UNSET_EMPTY "PCRE2_SUBSTITUTE_UNSET_EMPTY"
    cdef unsigned int SUBSTITUTE_UNKNOWN_UNSET "PCRE2_SUBSTITUTE_UNKNOWN_UNSET"
    cdef unsigned int SUBSTITUTE_OVERFLOW_LENGTH "PCRE2_SUBSTITUTE_OVERFLOW_LENGTH"
    cdef unsigned int NO_JIT "PCRE2_NO_JIT"
    cdef unsigned int NO_UTF_CHECK "PCRE2_NO_UTF_CHECK"
    cdef unsigned int COPY_MATCHED_SUBJECT "PCRE2_COPY_MATCHED_SUBJECT"
    cdef unsigned int SUBSTITUTE_LITERAL "PCRE2_SUBSTITUTE_LITERAL"
    cdef unsigned int SUBSTITUTE_MATCHED "PCRE2_SUBSTITUTE_MATCHED"
    cdef unsigned int SUBSTITUTE_REPLACEMENT_ONLY "PCRE2_SUBSTITUTE_REPLACEMENT_ONLY"
    
    # Error codes below are defined as contiguous ranges in PCRE2. This allows
    # for upper and lower bounds checks to determine class of error from error
    # code. For more details on error codes, see "pcre2.h".

    # Error codes returned from pcre2_compile(). Only compilation errors are
    # positive.
    cdef int ERROR_COMPILATION_MIN "PCRE2_ERROR_END_BACKSLASH"
    cdef int ERROR_END_BACKSLASH "PCRE2_ERROR_END_BACKSLASH"
    cdef int ERROR_END_BACKSLASH_C "PCRE2_ERROR_END_BACKSLASH_C"
    cdef int ERROR_UNKNOWN_ESCAPE "PCRE2_ERROR_UNKNOWN_ESCAPE"
    cdef int ERROR_QUANTIFIER_OUT_OF_ORDER "PCRE2_ERROR_QUANTIFIER_OUT_OF_ORDER"
    cdef int ERROR_QUANTIFIER_TOO_BIG "PCRE2_ERROR_QUANTIFIER_TOO_BIG"
    cdef int ERROR_MISSING_SQUARE_BRACKET "PCRE2_ERROR_MISSING_SQUARE_BRACKET"
    cdef int ERROR_ESCAPE_INVALID_IN_CLASS "PCRE2_ERROR_ESCAPE_INVALID_IN_CLASS"
    cdef int ERROR_CLASS_RANGE_ORDER "PCRE2_ERROR_CLASS_RANGE_ORDER"
    cdef int ERROR_QUANTIFIER_INVALID "PCRE2_ERROR_QUANTIFIER_INVALID"
    cdef int ERROR_INTERNAL_UNEXPECTED_REPEAT "PCRE2_ERROR_INTERNAL_UNEXPECTED_REPEAT"
    cdef int ERROR_INVALID_AFTER_PARENS_QUERY "PCRE2_ERROR_INVALID_AFTER_PARENS_QUERY"
    cdef int ERROR_POSIX_CLASS_NOT_IN_CLASS "PCRE2_ERROR_POSIX_CLASS_NOT_IN_CLASS"
    cdef int ERROR_POSIX_NO_SUPPORT_COLLATING "PCRE2_ERROR_POSIX_NO_SUPPORT_COLLATING"
    cdef int ERROR_MISSING_CLOSING_PARENTHESIS "PCRE2_ERROR_MISSING_CLOSING_PARENTHESIS"
    cdef int ERROR_BAD_SUBPATTERN_REFERENCE "PCRE2_ERROR_BAD_SUBPATTERN_REFERENCE"
    cdef int ERROR_NULL_PATTERN "PCRE2_ERROR_NULL_PATTERN"
    cdef int ERROR_BAD_OPTIONS "PCRE2_ERROR_BAD_OPTIONS"
    cdef int ERROR_MISSING_COMMENT_CLOSING "PCRE2_ERROR_MISSING_COMMENT_CLOSING"
    cdef int ERROR_PARENTHESES_NEST_TOO_DEEP "PCRE2_ERROR_PARENTHESES_NEST_TOO_DEEP"
    cdef int ERROR_PATTERN_TOO_LARGE "PCRE2_ERROR_PATTERN_TOO_LARGE"
    cdef int ERROR_HEAP_FAILED "PCRE2_ERROR_HEAP_FAILED"
    cdef int ERROR_UNMATCHED_CLOSING_PARENTHESIS "PCRE2_ERROR_UNMATCHED_CLOSING_PARENTHESIS"
    cdef int ERROR_INTERNAL_CODE_OVERFLOW "PCRE2_ERROR_INTERNAL_CODE_OVERFLOW"
    cdef int ERROR_MISSING_CONDITION_CLOSING "PCRE2_ERROR_MISSING_CONDITION_CLOSING"
    cdef int ERROR_LOOKBEHIND_NOT_FIXED_LENGTH "PCRE2_ERROR_LOOKBEHIND_NOT_FIXED_LENGTH"
    cdef int ERROR_ZERO_RELATIVE_REFERENCE "PCRE2_ERROR_ZERO_RELATIVE_REFERENCE"
    cdef int ERROR_TOO_MANY_CONDITION_BRANCHES "PCRE2_ERROR_TOO_MANY_CONDITION_BRANCHES"
    cdef int ERROR_CONDITION_ASSERTION_EXPECTED "PCRE2_ERROR_CONDITION_ASSERTION_EXPECTED"
    cdef int ERROR_BAD_RELATIVE_REFERENCE "PCRE2_ERROR_BAD_RELATIVE_REFERENCE"
    cdef int ERROR_UNKNOWN_POSIX_CLASS "PCRE2_ERROR_UNKNOWN_POSIX_CLASS"
    cdef int ERROR_INTERNAL_STUDY_ERROR "PCRE2_ERROR_INTERNAL_STUDY_ERROR"
    cdef int ERROR_UNICODE_NOT_SUPPORTED "PCRE2_ERROR_UNICODE_NOT_SUPPORTED"
    cdef int ERROR_PARENTHESES_STACK_CHECK "PCRE2_ERROR_PARENTHESES_STACK_CHECK"
    cdef int ERROR_CODE_POINT_TOO_BIG "PCRE2_ERROR_CODE_POINT_TOO_BIG"
    cdef int ERROR_LOOKBEHIND_TOO_COMPLICATED "PCRE2_ERROR_LOOKBEHIND_TOO_COMPLICATED"
    cdef int ERROR_LOOKBEHIND_INVALID_BACKSLASH_C "PCRE2_ERROR_LOOKBEHIND_INVALID_BACKSLASH_C"
    cdef int ERROR_UNSUPPORTED_ESCAPE_SEQUENCE "PCRE2_ERROR_UNSUPPORTED_ESCAPE_SEQUENCE"
    cdef int ERROR_CALLOUT_NUMBER_TOO_BIG "PCRE2_ERROR_CALLOUT_NUMBER_TOO_BIG"
    cdef int ERROR_MISSING_CALLOUT_CLOSING "PCRE2_ERROR_MISSING_CALLOUT_CLOSING"
    cdef int ERROR_ESCAPE_INVALID_IN_VERB "PCRE2_ERROR_ESCAPE_INVALID_IN_VERB"
    cdef int ERROR_UNRECOGNIZED_AFTER_QUERY_P "PCRE2_ERROR_UNRECOGNIZED_AFTER_QUERY_P"
    cdef int ERROR_MISSING_NAME_TERMINATOR "PCRE2_ERROR_MISSING_NAME_TERMINATOR"
    cdef int ERROR_DUPLICATE_SUBPATTERN_NAME "PCRE2_ERROR_DUPLICATE_SUBPATTERN_NAME"
    cdef int ERROR_INVALID_SUBPATTERN_NAME "PCRE2_ERROR_INVALID_SUBPATTERN_NAME"
    cdef int ERROR_UNICODE_PROPERTIES_UNAVAILABLE "PCRE2_ERROR_UNICODE_PROPERTIES_UNAVAILABLE"
    cdef int ERROR_MALFORMED_UNICODE_PROPERTY "PCRE2_ERROR_MALFORMED_UNICODE_PROPERTY"
    cdef int ERROR_UNKNOWN_UNICODE_PROPERTY "PCRE2_ERROR_UNKNOWN_UNICODE_PROPERTY"
    cdef int ERROR_SUBPATTERN_NAME_TOO_LONG "PCRE2_ERROR_SUBPATTERN_NAME_TOO_LONG"
    cdef int ERROR_TOO_MANY_NAMED_SUBPATTERNS "PCRE2_ERROR_TOO_MANY_NAMED_SUBPATTERNS"
    cdef int ERROR_CLASS_INVALID_RANGE "PCRE2_ERROR_CLASS_INVALID_RANGE"
    cdef int ERROR_OCTAL_BYTE_TOO_BIG "PCRE2_ERROR_OCTAL_BYTE_TOO_BIG"
    cdef int ERROR_INTERNAL_OVERRAN_WORKSPACE "PCRE2_ERROR_INTERNAL_OVERRAN_WORKSPACE"
    cdef int ERROR_INTERNAL_MISSING_SUBPATTERN "PCRE2_ERROR_INTERNAL_MISSING_SUBPATTERN"
    cdef int ERROR_DEFINE_TOO_MANY_BRANCHES "PCRE2_ERROR_DEFINE_TOO_MANY_BRANCHES"
    cdef int ERROR_BACKSLASH_O_MISSING_BRACE "PCRE2_ERROR_BACKSLASH_O_MISSING_BRACE"
    cdef int ERROR_INTERNAL_UNKNOWN_NEWLINE "PCRE2_ERROR_INTERNAL_UNKNOWN_NEWLINE"
    cdef int ERROR_BACKSLASH_G_SYNTAX "PCRE2_ERROR_BACKSLASH_G_SYNTAX"
    cdef int ERROR_PARENS_QUERY_R_MISSING_CLOSING "PCRE2_ERROR_PARENS_QUERY_R_MISSING_CLOSING"
    cdef int ERROR_VERB_ARGUMENT_NOT_ALLOWED "PCRE2_ERROR_VERB_ARGUMENT_NOT_ALLOWED"
    cdef int ERROR_VERB_UNKNOWN "PCRE2_ERROR_VERB_UNKNOWN"
    cdef int ERROR_SUBPATTERN_NUMBER_TOO_BIG "PCRE2_ERROR_SUBPATTERN_NUMBER_TOO_BIG"
    cdef int ERROR_SUBPATTERN_NAME_EXPECTED "PCRE2_ERROR_SUBPATTERN_NAME_EXPECTED"
    cdef int ERROR_INTERNAL_PARSED_OVERFLOW "PCRE2_ERROR_INTERNAL_PARSED_OVERFLOW"
    cdef int ERROR_INVALID_OCTAL "PCRE2_ERROR_INVALID_OCTAL"
    cdef int ERROR_SUBPATTERN_NAMES_MISMATCH "PCRE2_ERROR_SUBPATTERN_NAMES_MISMATCH"
    cdef int ERROR_MARK_MISSING_ARGUMENT "PCRE2_ERROR_MARK_MISSING_ARGUMENT"
    cdef int ERROR_INVALID_HEXADECIMAL "PCRE2_ERROR_INVALID_HEXADECIMAL"
    cdef int ERROR_BACKSLASH_C_SYNTAX "PCRE2_ERROR_BACKSLASH_C_SYNTAX"
    cdef int ERROR_BACKSLASH_K_SYNTAX "PCRE2_ERROR_BACKSLASH_K_SYNTAX"
    cdef int ERROR_INTERNAL_BAD_CODE_LOOKBEHINDS "PCRE2_ERROR_INTERNAL_BAD_CODE_LOOKBEHINDS"
    cdef int ERROR_BACKSLASH_N_IN_CLASS "PCRE2_ERROR_BACKSLASH_N_IN_CLASS"
    cdef int ERROR_CALLOUT_STRING_TOO_LONG "PCRE2_ERROR_CALLOUT_STRING_TOO_LONG"
    cdef int ERROR_UNICODE_DISALLOWED_CODE_POINT "PCRE2_ERROR_UNICODE_DISALLOWED_CODE_POINT"
    cdef int ERROR_UTF_IS_DISABLED "PCRE2_ERROR_UTF_IS_DISABLED"
    cdef int ERROR_UCP_IS_DISABLED "PCRE2_ERROR_UCP_IS_DISABLED"
    cdef int ERROR_VERB_NAME_TOO_LONG "PCRE2_ERROR_VERB_NAME_TOO_LONG"
    cdef int ERROR_BACKSLASH_U_CODE_POINT_TOO_BIG "PCRE2_ERROR_BACKSLASH_U_CODE_POINT_TOO_BIG"
    cdef int ERROR_MISSING_OCTAL_OR_HEX_DIGITS "PCRE2_ERROR_MISSING_OCTAL_OR_HEX_DIGITS"
    cdef int ERROR_VERSION_CONDITION_SYNTAX "PCRE2_ERROR_VERSION_CONDITION_SYNTAX"
    cdef int ERROR_INTERNAL_BAD_CODE_AUTO_POSSESS "PCRE2_ERROR_INTERNAL_BAD_CODE_AUTO_POSSESS"
    cdef int ERROR_CALLOUT_NO_STRING_DELIMITER "PCRE2_ERROR_CALLOUT_NO_STRING_DELIMITER"
    cdef int ERROR_CALLOUT_BAD_STRING_DELIMITER "PCRE2_ERROR_CALLOUT_BAD_STRING_DELIMITER"
    cdef int ERROR_BACKSLASH_C_CALLER_DISABLED "PCRE2_ERROR_BACKSLASH_C_CALLER_DISABLED"
    cdef int ERROR_QUERY_BARJX_NEST_TOO_DEEP "PCRE2_ERROR_QUERY_BARJX_NEST_TOO_DEEP"
    cdef int ERROR_BACKSLASH_C_LIBRARY_DISABLED "PCRE2_ERROR_BACKSLASH_C_LIBRARY_DISABLED"
    cdef int ERROR_PATTERN_TOO_COMPLICATED "PCRE2_ERROR_PATTERN_TOO_COMPLICATED"
    cdef int ERROR_LOOKBEHIND_TOO_LONG "PCRE2_ERROR_LOOKBEHIND_TOO_LONG"
    cdef int ERROR_PATTERN_STRING_TOO_LONG "PCRE2_ERROR_PATTERN_STRING_TOO_LONG"
    cdef int ERROR_INTERNAL_BAD_CODE "PCRE2_ERROR_INTERNAL_BAD_CODE"
    cdef int ERROR_INTERNAL_BAD_CODE_IN_SKIP "PCRE2_ERROR_INTERNAL_BAD_CODE_IN_SKIP"
    cdef int ERROR_NO_SURROGATES_IN_UTF16 "PCRE2_ERROR_NO_SURROGATES_IN_UTF16"
    cdef int ERROR_BAD_LITERAL_OPTIONS "PCRE2_ERROR_BAD_LITERAL_OPTIONS"
    cdef int ERROR_SUPPORTED_ONLY_IN_UNICODE "PCRE2_ERROR_SUPPORTED_ONLY_IN_UNICODE"
    cdef int ERROR_INVALID_HYPHEN_IN_OPTIONS "PCRE2_ERROR_INVALID_HYPHEN_IN_OPTIONS"
    cdef int ERROR_ALPHA_ASSERTION_UNKNOWN "PCRE2_ERROR_ALPHA_ASSERTION_UNKNOWN"
    cdef int ERROR_SCRIPT_RUN_NOT_AVAILABLE "PCRE2_ERROR_SCRIPT_RUN_NOT_AVAILABLE"
    cdef int ERROR_TOO_MANY_CAPTURES "PCRE2_ERROR_TOO_MANY_CAPTURES"
    cdef int ERROR_CONDITION_ATOMIC_ASSERTION_EXPECTED "PCRE2_ERROR_CONDITION_ATOMIC_ASSERTION_EXPECTED"
    cdef int ERROR_BACKSLASH_K_IN_LOOKAROUND "PCRE2_ERROR_BACKSLASH_K_IN_LOOKAROUND"
    cdef int ERROR_COMPILATION_MAX "PCRE2_ERROR_BACKSLASH_K_IN_LOOKAROUND"

    # Error codes for expected matching errors: no match and partial match. All
    # matching errors are negative.
    cdef int ERROR_MATCHING_MAX "PCRE2_ERROR_NOMATCH"
    cdef int ERROR_NOMATCH "PCRE2_ERROR_NOMATCH"
    cdef int ERROR_PARTIAL "PCRE2_ERROR_PARTIAL"
    cdef int ERROR_MATCHING_MIN "PCRE2_ERROR_PARTIAL"

    # Error codes for unicode validity checks. All unicode error codes are
    # negative.
    cdef int ERROR_UNICODE_MAX "PCRE2_ERROR_UTF8_ERR1"
    cdef int ERROR_UTF8_ERR1 "PCRE2_ERROR_UTF8_ERR1"
    cdef int ERROR_UTF8_ERR2 "PCRE2_ERROR_UTF8_ERR2"
    cdef int ERROR_UTF8_ERR3 "PCRE2_ERROR_UTF8_ERR3"
    cdef int ERROR_UTF8_ERR4 "PCRE2_ERROR_UTF8_ERR4"
    cdef int ERROR_UTF8_ERR5 "PCRE2_ERROR_UTF8_ERR5"
    cdef int ERROR_UTF8_ERR6 "PCRE2_ERROR_UTF8_ERR6"
    cdef int ERROR_UTF8_ERR7 "PCRE2_ERROR_UTF8_ERR7"
    cdef int ERROR_UTF8_ERR8 "PCRE2_ERROR_UTF8_ERR8"
    cdef int ERROR_UTF8_ERR9 "PCRE2_ERROR_UTF8_ERR9"
    cdef int ERROR_UTF8_ERR10 "PCRE2_ERROR_UTF8_ERR10"
    cdef int ERROR_UTF8_ERR11 "PCRE2_ERROR_UTF8_ERR11"
    cdef int ERROR_UTF8_ERR12 "PCRE2_ERROR_UTF8_ERR12"
    cdef int ERROR_UTF8_ERR13 "PCRE2_ERROR_UTF8_ERR13"
    cdef int ERROR_UTF8_ERR14 "PCRE2_ERROR_UTF8_ERR14"
    cdef int ERROR_UTF8_ERR15 "PCRE2_ERROR_UTF8_ERR15"
    cdef int ERROR_UTF8_ERR16 "PCRE2_ERROR_UTF8_ERR16"
    cdef int ERROR_UTF8_ERR17 "PCRE2_ERROR_UTF8_ERR17"
    cdef int ERROR_UTF8_ERR18 "PCRE2_ERROR_UTF8_ERR18"
    cdef int ERROR_UTF8_ERR19 "PCRE2_ERROR_UTF8_ERR19"
    cdef int ERROR_UTF8_ERR20 "PCRE2_ERROR_UTF8_ERR20"
    cdef int ERROR_UTF8_ERR21 "PCRE2_ERROR_UTF8_ERR21"

    cdef int ERROR_UTF16_ERR1 "PCRE2_ERROR_UTF16_ERR1"
    cdef int ERROR_UTF16_ERR2 "PCRE2_ERROR_UTF16_ERR2"
    cdef int ERROR_UTF16_ERR3 "PCRE2_ERROR_UTF16_ERR3"
    
    cdef int ERROR_UTF32_ERR1 "PCRE2_ERROR_UTF32_ERR1"
    cdef int ERROR_UTF32_ERR2 "PCRE2_ERROR_UTF32_ERR2"
    cdef int ERROR_UNICODE_MIN "PCRE2_ERROR_UTF32_ERR2"

    
    # Miscellaneous error codes. All miscellaneous errors are negative.
    cdef int ERROR_MISC_MAX "PCRE2_ERROR_BADDATA"
    cdef int ERROR_BADDATA "PCRE2_ERROR_BADDATA"
    cdef int ERROR_MIXEDTABLES "PCRE2_ERROR_MIXEDTABLES"
    cdef int ERROR_BADMAGIC "PCRE2_ERROR_BADMAGIC"
    cdef int ERROR_BADMODE "PCRE2_ERROR_BADMODE"
    cdef int ERROR_BADOFFSET "PCRE2_ERROR_BADOFFSET"
    cdef int ERROR_BADOPTION "PCRE2_ERROR_BADOPTION"
    cdef int ERROR_BADREPLACEMENT "PCRE2_ERROR_BADREPLACEMENT"
    cdef int ERROR_BADUTFOFFSET "PCRE2_ERROR_BADUTFOFFSET"
    cdef int ERROR_CALLOUT "PCRE2_ERROR_CALLOUT"
    cdef int ERROR_DFA_BADRESTART "PCRE2_ERROR_DFA_BADRESTART"
    cdef int ERROR_DFA_RECURSE "PCRE2_ERROR_DFA_RECURSE"
    cdef int ERROR_DFA_UCOND "PCRE2_ERROR_DFA_UCOND"
    cdef int ERROR_DFA_UFUNC "PCRE2_ERROR_DFA_UFUNC"
    cdef int ERROR_DFA_UITEM "PCRE2_ERROR_DFA_UITEM"
    cdef int ERROR_DFA_WSSIZE "PCRE2_ERROR_DFA_WSSIZE"
    cdef int ERROR_INTERNAL "PCRE2_ERROR_INTERNAL"
    cdef int ERROR_JIT_BADOPTION "PCRE2_ERROR_JIT_BADOPTION"
    cdef int ERROR_JIT_STACKLIMIT "PCRE2_ERROR_JIT_STACKLIMIT"
    cdef int ERROR_MATCHLIMIT "PCRE2_ERROR_MATCHLIMIT"
    cdef int ERROR_NOMEMORY "PCRE2_ERROR_NOMEMORY"
    cdef int ERROR_NOSUBSTRING "PCRE2_ERROR_NOSUBSTRING"
    cdef int ERROR_NOUNIQUESUBSTRING "PCRE2_ERROR_NOUNIQUESUBSTRING"
    cdef int ERROR_NULL "PCRE2_ERROR_NULL"
    cdef int ERROR_RECURSELOOP "PCRE2_ERROR_RECURSELOOP"
    cdef int ERROR_DEPTHLIMIT "PCRE2_ERROR_DEPTHLIMIT"
    cdef int ERROR_RECURSIONLIMIT "PCRE2_ERROR_RECURSIONLIMIT"
    cdef int ERROR_UNAVAILABLE "PCRE2_ERROR_UNAVAILABLE"
    cdef int ERROR_UNSET "PCRE2_ERROR_UNSET"
    cdef int ERROR_BADOFFSETLIMIT "PCRE2_ERROR_BADOFFSETLIMIT"
    cdef int ERROR_BADREPESCAPE "PCRE2_ERROR_BADREPESCAPE"
    cdef int ERROR_REPMISSINGBRACE "PCRE2_ERROR_REPMISSINGBRACE"
    cdef int ERROR_BADSUBSTITUTION "PCRE2_ERROR_BADSUBSTITUTION"
    cdef int ERROR_BADSUBSPATTERN "PCRE2_ERROR_BADSUBSPATTERN"
    cdef int ERROR_TOOMANYREPLACE "PCRE2_ERROR_TOOMANYREPLACE"
    cdef int ERROR_BADSERIALIZEDDATA "PCRE2_ERROR_BADSERIALIZEDDATA"
    cdef int ERROR_HEAPLIMIT "PCRE2_ERROR_HEAPLIMIT"
    cdef int ERROR_CONVERT_SYNTAX "PCRE2_ERROR_CONVERT_SYNTAX"
    cdef int ERROR_INTERNAL_DUPMATCH "PCRE2_ERROR_INTERNAL_DUPMATCH"
    cdef int ERROR_DFA_UINVALID_UTF "PCRE2_ERROR_DFA_UINVALID_UTF"
    cdef int ERROR_MISC_MIN "PCRE2_ERROR_DFA_UINVALID_UTF"


    # Opaque handles for PCRE2 defined structs.
    ctypedef struct code_t "pcre2_code":
        pass
    ctypedef struct match_data_t "pcre2_match_data":
        pass
    ctypedef struct general_context_t "pcre2_general_context":
        pass
    ctypedef struct compile_context_t "pcre2_compile_context":
        pass
    ctypedef struct match_context_t "pcre2_match_context":
        pass

    # Basic string definition. Note that this assumes PCRE2 in compiled to
    # support 8-bit strings.
    ctypedef const uint8_t *sptr_t "PCRE2_SPTR"

    
    # Error handling functions.
    int get_error_message "pcre2_get_error_message" (
        int errorcode,
        uint8_t *buffer,
        size_t bufflen);

    # Pattern compilation functions.
    code_t * compile "pcre2_compile" (
        sptr_t pattern, 
        size_t length,
        uint32_t options,
        int *errorcode,
        size_t *erroroffset,
        compile_context_t *ccontext)

    void code_free "pcre2_code_free"(code_t *code)

    # Information on compiled pattern.
    int pattern_info "pcre2_pattern_info" (
        const code_t *code,
        uint32_t what,
        void *where)
    
    # Matching and match data functions.
    match_data_t * match_data_create "pcre2_match_data_create" (
        uint32_t ovecsize,
        general_context_t *gcontext)
    
    match_data_t * match_data_create_from_pattern "pcre2_match_data_create_from_pattern" (
        const code_t *code,
        general_context_t *gcontext)
    
    int match "pcre2_match" (
        const code_t *code,
        sptr_t subject,
        size_t length,
        size_t startoffset,
        uint32_t options,
        match_data_t *match_data,
        match_context_t *mcontext)
    
    void match_data_free "pcre2_match_data_free" (match_data_t *match_data)

    # String extraction from match data blocks.
    int substring_get_byname "pcre2_substring_get_byname" (
        match_data_t *match_data,
        sptr_t name, 
        uint8_t **bufferptr,
        size_t *bufflen)

    int substring_get_bynumber "pcre2_substring_get_bynumber" (
        match_data_t *match_data,
        uint32_t number,
        uint8_t **bufferptr,
        size_t *bufflen)

    # Substitution.
    int substitute "pcre2_substitute" (
        const code_t *code,
        sptr_t subject,
        size_t length,
        size_t startoffset,
        uint32_t options,
        match_data_t *match_data,
        match_context_t *mcontext,
        sptr_t replacement,
        size_t rlength,
        uint8_t *outputbuffer,
        size_t *outlengthptr)

